name: ValourLink
version: 1.0
main: gg.valour.minecraft.ValourLink
api-version: 1.13
depend: [Vault]
load: STARTUP
commands:
  valourlink:
    description: Starts the Valour link process
    usage: /<command>
    permission: valour.link