name: ValourLink
version: 1.0
main: gg.valour.minecraft.ValourLink
api-version: 1.13
depend: [Vault]
load: STARTUP
commands:
  valourlink:
    description: Starts the Valour link process
    usage: /<command>
    permission: valour.link
  valourid:
    description: Provides your Valour id, if linked
    usage: /<command>
    permission: valour.id
  balance:
    description: Provides your Valour balance
    usage: /<command>
    permission: valour.balance
    aliases: bal, vbal
  pay:
    description: Sends an amount from your balance to the given player
    usage: /<command> <player> <amount>
    permission: valour.pay
    aliases: vpay